name: GeneratePDF

on:
  push

jobs:
  generate_pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node v15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Generate PDF Action
        uses: tylermneher/resume-tylermneher-gh-action@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
