name: GeneratePDF

on: [push]

jobs:
  generate_pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Generate PDF Action
        uses: tylermneher/resume-tylermneher-gh-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm ci
      - run: npm test
