name: GeneratePDF

on:
  push:
    branches:
      - main

jobs:
  generate_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node v15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Generate PDF Action
        uses: tylermneher/resume-tylermneher-gh-action@main
        with:
          GITHUB_TOKEN: ${{secrets.MY_TOKEN}}
